### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by Zakkery** [lior-k/fast-elasticsearch-vector-scoring#1]
Hi,
I am relatively new to elasticsearch plugins, and I really appreciate your plugin but I couldn't make elasticsearch work with it.
I installed elasticsearch version 2.4.4 like you mentioned and compiled plugin using maven. When I tried to put it in plugins/ directory and run elasticsearch, I got an error
> Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-binary-vector-scoring-2.4.4.jar]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.FileSystemException: plugins/elasticsearch-binary-vector-scoring-2.4.4.jar/plugin-descriptor.properties: Not a directory

So I repackaged it as a folder with the following structure
__ fast-elasticsearch-vector-scoring/
__|-> elasticsearch-binary-vector-scoring-2.4.4.jar
__|-> plugin-descriptor.properties

Where plugin-descriptor.properties is a file I created manually that contains:
> description=ElasticSearch Plugin for Binary Vector Scoring
version=2.4.4
name=VectorScoringPlugin
jvm=true
classname=com.liorkn.elasticsearch.plugin.VectorScoringPlugin
java.version=9
elasticsearch.version=2.4.4

Now, when I run elasticsearch it seems to load the plugin without any errors, however, when I try to use it I get the following error trace:
> nested: QueryParsingException[script_score the script could not be loaded]; nested: ScriptException[scripts of type [inline], operation [search] and lang [knn] are disabled]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: ScriptException[scripts of type [inline], operation [search] and lang [knn] are disabled]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:244)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:456)
	at org.elasticsearch.index.query.functionscore.script.ScriptScoreFunctionParser.parse(ScriptScoreFunctionParser.java:104)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parse(FunctionScoreQueryParser.java:140)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:324)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:224)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:219)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:856)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:667)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:377)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

Did I miss something when building a jar file?

Thanks in advance,
Best,
Zakkery

**Comment by lior-k** [comment]
You need to enable scripting in config/elasticsearch.yml:
```
script.inline: true
script.indexed: true
```

**Comment by Zakkery** [comment]
Awesome, yeah, I guess I forgot about that! Thank you for your help!

**Comment by lior-k** [comment]
No problem. Feel free to add the missing properties file to the repo

**Comment by lior-k** [comment]
Fixed at PR #2
