### ISSUE TITLE
plugin not installing

### ISSUE THREAD

**Issue by varunraj1493** [lior-k/fast-elasticsearch-vector-scoring#27]
Hi I am using E.S 5.6.9 and want to use this plugin. Facing this error while installing 

 Downloading file:/home/vljklkj/Desktop/fast-elasticsearch-vector-scoring/target/releases/elasticsearch-binary-vector-scoring-5.6.9.zip
[=================================================] 100%   
ERROR: `elasticsearch` directory is missing in the plugin zip

I cloned the project, changed ES version to 5.6.9 in POM files and did mvn clean. Got a zip file and ran this command to install the plugin.
"sudo bin/elasticsearch-plugin install file:/home/vljklkj/Desktop/fast-elasticsearch-vector-scoring/target/releases/elasticsearch-binary-vector-scoring-5.6.9.zip"

please help me solve this issue as early as possible.... thanks in advance.

**Comment by varunraj1493** [comment]
i also tried by changing folder name to elasticsearch.zip, didn't work....

**Comment by lior-k** [comment]
You're missing a `/`, try running it like this:
'sudo bin/elasticsearch-plugin install file://home/vljklkj/Desktop/fast-elasticsearch-vector-scoring/target/releases/elasticsearch-binary-vector-scoring-5.6.9.zip'

**Comment by varunraj1493** [comment]
Hi, i changed as per your instructions but now getting new error

-> Downloading file://home/nm,m/Desktop/fast-elasticsearch-vector-scoring/target/releases/elasticsearch-binary-vector-scoring-5.6.9.zip
Exception in thread "main" java.net.UnknownHostException: home
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:400)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:328)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:248)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by michaeltansytp** [comment]
same problem occurs to mine. Has the solution to it?

**Comment by lior-k** [comment]
Hi guys, I'm checking it

**Comment by michaeltansytp** [comment]
hi @lior-k it's solved already. We can directly copy all files inside the zip to elasticsearch/plugins and it works perfectly.

**Comment by lior-k** [comment]
Thanks for the tip @michaeltansytp 
I fixed the issue. you can now follow the installation as stated in the readme file. Let me know if you find this useful.

**Comment by varunraj1493** [comment]
Hi , sorry for the late reply. I tried the solution suggested by @michaeltansytp and ES wasn't starting. 
@michaeltansytp  can you share the zip file or the files you're having inside the zip. 

Need your help @lior-k

**Comment by lior-k** [comment]
This issue is solved. Git pull and try without any work around. Just follow the instructions in the Readme

**Comment by varunraj1493** [comment]
Tried , got error. It worked when i added one more "/" for file path

./bin/elasticsearch-plugin install file:///home/varun/Downloads/elasticSearchPlugins/fast-elasticsearch-vector-scoring/target/releases/elasticsearch-binary-vector-scoring-5.6.9.zip

Thanks @lior-k

**Comment by varunraj1493** [comment]
Working, thanks @lior-k
