### ISSUE TITLE
Plugin is not installed on elasticsearch 7.5.2

### ISSUE THREAD

**Issue by abashkinas** [lior-k/fast-elasticsearch-vector-scoring#56]
Hello, we are currently using elasticsearch version 7.5.2, I have compiled a zip file from the 7.5.0 branch.
When trying to install this plugin, I get the error:

Exception in thread "main" java.lang.IllegalArgumentException: Plugin [elasticsearch-binary-vector-scoring] was built for Elasticsearch version 7.5.0 but version 7.5.2 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:728)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:803)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:786)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:232)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

Please tell me how to install this plugin on elasticsearch version 7.5.2?

**Comment by lior-k** [comment]
just pushed a new branch for it called `es-7.5.2`
please use that
